### ISSUE TITLE
IRMDB export issues found during SSRM2024

### ISSUE THREAD

**Issue by duserzym** [PmagPy/RockmagPy-notebooks#30]
1. MPMS data export from the BigRed in MagIC format does not have <meas_freq> values. 
2. VSM data export from the LakeShore for backfield experiment is labeled in the <experiment> and <instrument_codes> columns to be VSM4 instead of VSM3. 
3. Demag_GUI currently cannot parse the measurement file (Yiming will look into this)

**Comment by Swanson-Hysell** [comment]
Each specimen/sample needs to have a method code. We can do this through the following approach:
- If the specimen from the IRM database has a mass associated with it, give it the method code: LP-MASS
- If it has a volume: LP-VOL
- If it has neither: LP-NONE

Since we determined that the Verwey temperature determination is being done using second derivative zero crossing in Quantum Ferret, it should have the method code SM-2DZERO rather than SM-1DMAX

**Comment by maxwellbrown** [comment]
This seems like a good approach for masses and volumes. All specimens in IRMdb will have a mass, some may have both mass and volume.

**Comment by peat22** [comment]
> Each specimen/sample needs to have a method code. We can do this through the following approach:
> 
>     * If the specimen from the IRM database has a mass associated with it, give it the method code: LP-MASS
> 
>     * If it has a volume: LP-VOL
> 
>     * If it has neither: LP-NONE
> 

Done

> 
> Since we determined that the Verwey temperature determination is being done using second derivative zero crossing in Quantum Ferret, it should have the method code SM-2DZERO rather than SM-1DMAX

I will work on this in the Quantum ferret tomorrow

**Comment by peat22** [comment]
> 1. MPMS data export from the BigRed in MagIC format does not have <meas_freq> values.
>
Can't remember if I looked into this already, check tomorrow
 
>     2. VSM data export from the LakeShore for backfield experiment is labeled in the  and <instrument_codes> columns to be VSM4 instead of VSM3.
> 
VSM4 is correct

>     3. Demag_GUI currently cannot parse the measurement file (Yiming will look into this)
> 
>     4. in the 2G data export, the <method_codes> column needs information more than lab protocols (such as LP-DIR-AF), it needs to be LT-AF-Z:LP-DIR-AF because the program filters for a lab treatment that is done in zero field and that the lab protocol is measuring directional data with AF steps
> 
This depends on what people choose when they do the measurements. If they choose wrong, or don't choose the export can not determine what codes should be added

>     5. In the 2G export measurement file, it is necessary to have 'g' or 'b' for good or bad measurements in the  column. Currently the column is empty. This causes demag_gui to have issues loading the data

Done, however not all measurements are 'good', some are Chaotic Neutral
> 
>     6. In the 2G export measurement file, it is necessary to have entry in the  column with unique entry for each measurement row. demag_gui uses this unique indexing to mark good and bad measurements.

I'll look into this

**Comment by peat22** [comment]
1. MPMS data export from the BigRed in MagIC format does not have <meas_freq> values.

      ---This was fixed a while ago

6. In the 2G export measurement file, it is necessary to have entry in the column with unique entry for each measurement row. demag_gui uses this unique indexing to mark good and bad measurements

      ---Ok, this is added in measurements.measurement

Since we determined that the Verwey temperature determination is being done using second derivative zero crossing in Quantum Ferret, it should have the method code SM-2DZERO rather than SM-1DMAX

     ---Done

4. in the 2G data export, the <method_codes> column needs information more than lab protocols (such as LP-DIR-AF), it needs to be LT-AF-Z:LP-DIR-AF because the program filters for a lab treatment that is done in zero field and that the lab protocol is measuring directional data with AF steps

    --- Done, may need to adjust others. However, on export, I can only assign codes if there is equivalent info in our database. 

    * In order to pass validation, there needs to be an entry in the specimen "citations" column. This entry should be "This study" by default

   --- I looked into this further. The 3.0 data model states:
         The value in this column is included in downloaded contributions, but is ignored in uploaded contributions.

**Comment by peat22** [comment]
So I think the only outstanding issue from the above is:

    critical_temp_type requires that values come from a controlled vocabulary

but let me know if I am wrong

**Comment by Swanson-Hysell** [comment]
@rminnett do you have insight here on the point below? I had a contribution where it wasn't passing validation given the lack of an entry in the citations column. However, Peak writes *I looked into this further. The 3.0 data model states:
The value in this column is included in downloaded contributions, but is ignored in uploaded contributions.*: :
> In order to pass validation, there needs to be an entry in the specimen "citations" column. This entry should be "This study" by default
--- **I looked into this further. The 3.0 data model states:
The value in this column is included in downloaded contributions, but is ignored in uploaded contributions.**

**Comment by Swanson-Hysell** [comment]
> So I think the only outstanding issue from the above is:
> 
> ```
> critical_temp_type requires that values come from a controlled vocabulary
> ```
> 
> but let me know if I am wrong

The available values (https://www2.earthref.org/vocabularies/controlled) for this category are currently:
- Alteration
- Blocking
- Curie
- Ferrimagnetic Pyrrhotite
- Hopkinson
- Magnetocrystalline Isotropic
- Morin
- Neel
- Phase Transition
- Pyrrhotite
- Spin Glass
- Unblocking
- Unknown
- Verwey

**Comment by Swanson-Hysell** [comment]
@peat22 This critical_temp_type issue remains. `Verwey transition` is output rather than `Verwey` which throws a validation error.

**Comment by peat22** [comment]
I have updated our table of critical temperature types to the following:
1	Neel
2	Blocking
3	Magnetocrystalline isotropic
4	Verwey
5	Morin
6	Phase Transition
7	Besnus
8	Alteration
9	Curie
10	Ferrimagnetic Pyrrhotite
11	Hopkinson
12	Pyrrhotite
13	Spin Glass
14	Unblocking
99	unknown

A couple questions:
Is Besnus not cannon for Ferrimagnetic Pyrrhotite these days? 
Whats the difference between Blocking and Unblocking?

**Comment by Swanson-Hysell** [comment]
I agree that Benus would be good to have on there (and can be considered canonical). We can update the controlled vocabularies.
